### ISSUE TITLE
VIsualize a complete pipeline

### ISSUE THREAD

**Issue by jl-wynen** [scipp/sciline#181] opened 2024-09-11 13:45 UTC
We have a number of pipelines across multiple projects now. And we compose new pipelines from them. It is currently very difficult to inspect a pipeline in its entirety to, e.g., find out what it can produce, or how it does a certain operation. It would be a great help if we could just visualize a pipeline without having to already know what it can produce or what products depend on the subgraph you are currently interested in.

**Comment by nvaytet** [comment] 2024-09-11 20:45
Duplicate of #177 ?

**Closed** 2024-09-12 08:44 UTC
