### ISSUE TITLE
Handling ``TypeVar`` with constraints of ``Generic`` providers.

### ISSUE THREAD

**Issue by YooSunYoung** [scipp/sciline#68] opened 2023-10-24 14:12 UTC
As mentioned in the PR #67,
consistent way of handling constraints of a ``TypeVar`` should be discussed.

## Context
Currently, constraints of ``TypeVar`` do not have any affect.
And existing ``Generic`` provider with ``TypeVar`` does not allow to have another provider with the same ``Generic`` type but with a specific type argument.

For instance following example does not work due to multiple providers:
```python
import sciline as sl
from typing import TypeVar, NewType

A = NewType('A', str)
B = NewType('B', str)
C = NewType('C', str)

T = TypeVar('T', A, B)

class H(sl.Scope[T, str], str):
    pass

def p1(x: T) -> H[T]:
    return f"H[{x}]"

def p2(x: C) -> H[C]:
    return "H[C]"

sl.Pipeline(
    [p1, p2], params={A: 'A', B: 'B', C: 'C'}
).compute(H[C])  # Raises ambiguous provider error.
```

Therefore @jokasimr suggested to allow specific type argument in the ``Generic`` type that are not in the constraints of the ``TypeVar`` type argument.

With that fix in PR #67, the above example would work.

## Discussions
Here is the summary of the discussion:

@SimonHeybrock suggested not to consider any ``Constraints`` and always prioritize a specific type argument to a ``TypeVar`` type argument instead.

No effect of constraints of ``TypeVar`` may be confusing to users as @jokasimr mentioned,
so I suggested to restrict the usage of the generic provider to the certain types that are in the constraints.

i.e. This following example should fail.
```python
S1 = NewType("S1", str)
S2 = NewType("S2", str)
S3 = NewType("S3", str)

S12 = TypeVar("T", S1, S2)

class H(sl.Scope[V, str], str):
    ...

def p12(S12) -> H[S12]
   ...

pl = sl.Pipeline(p12, params={S1: 'S1', S2:'S2', S3:'S3'})
pl.compute(H[S3])  # Should raise provider not found error
```

One concern @SimonHeybrock raised was that the providers, `p12` in this case, may not be used in the broader scope.

My opinion is that if the provider is meant to be flexible enough to be used in other scopes, then the ``TypeVar`` argument should have ``bound`` instead of ``constraints``.
In this way, we can both define ``strict`` providers and ``flexible`` providers.

## Suggested Solutions
Here are the summary of suggested solutions with **conflicts** to be resolved.

-  Allow multiple providers of the same ``Generic`` type only if the type argument constraints are not conflicting.
- ``constraints`` of ``TypeVar`` has no effect and always prioritize another ``Generic`` provider with specific type arguments.
- ``Generic`` provider with ``TypeVar`` can only be bound to the certain type sin its own ``constraints``.

**Comment by SimonHeybrock** [comment] 2023-10-25 05:46
> Here is the summary of the discussion:
> 
> @SimonHeybrock suggested not to consider any `Constraints` and always prioritize a specific type argument to a `TypeVar` type argument instead.

That was not really my point, did not not suggest to *not* consider constraints. There are really two independent (but partially overlapping) concerns:

1. Being able to specialize a provider (with a specific type argument). My point was that this might address 90% of uses in practice.
2. Considering constraints. This is of major importance/consequence, even if we completely ignore the question of using it for resolving conflicts (this would simply come as a side effect).

I think we should separate the discussions. I think (1) can be done anyway, will solve some usability hurdles and is not in conflict with whatever the outcome of (2) will be.

**Comment by YooSunYoung** [comment] 2023-10-25 07:44
> That was not really my point, I did not suggest to not consider constraints. There are really two independent (but partially overlapping) concerns
Thank you for clarifying ...! I'll move (1) to another issue then.

**Comment by jokasimr** [comment] 2024-02-06 11:01
I think like @SimonHeybrock said above the majority of use cases was already addressed by allowing specialized providers as was done in #69 .
The outstanding issue here is the question of considering constraints on the provider types.
The use case for that (as I understand it) is to be able to create a provider that handles a subset of cases, see for example this code, a variant of the example @YooSunYoung wrote above:
```python
from typing import NewType, TypeVar
import sciline as sl

S1 = NewType("S1", str)
S2 = NewType("S2", str)
S3 = NewType("S3", str)

S12 = TypeVar("S12", S1, S2)
S13 = TypeVar("S12", S1, S3)

class H(sl.Scope[S, str], str):
    pass

def p12(s12: S12) -> H[S12]:
    return 'p12'

def p1(s1: S1) -> H[S1]:
    return 'p1'

def p13(s13: S13) -> H[S13]:
    return 'p13'

pl = sl.Pipeline([p12, p1, p13], params={S1: 'S1', S2:'S2', S3:'S3'})
pl.compute(H[S1]) # Returns p1 <- this case was addressed in #69
pl.compute(H[S2]) # Currently raises ambiguous provider error
pl.compute(H[S3]) # Currently raises ambiguous provider error
```

If we consider the restrictions on the type vars then none of the cases above are actually ambiguous.
However, I have not encountered an example where this kind of structure was required to model the relationships between types in a workflow.
So unless anyone else can come up with a concrete example where this would be useful **I suggest we close this for now** and reopen if we encounter such a case.
If we do decide to fix this in the future I think the code in #67 might be a good starting point.

**Comment by SimonHeybrock** [comment] 2024-02-07 06:07
I think we should not primarily worry about resolving conflicts. Instead consider:

```python
from dataclasses import dataclass
from typing import TypeVar, Generic
import sciline

T = TypeVar('T', int, float)

@dataclass
class MyType(Generic[T]):
    value: T

def process(value: T) -> MyType[T]:
    return MyType(value)

pipeline = sciline.Pipeline((process, ))
pipeline[str] = 'abc'

pipeline.get(MyType[str])
```

Currently this works! But we think it should not, because `MyType` says it can only work with `int` and `float`. Sciline should prevent this.

**Comment by jokasimr** [comment] 2024-02-07 07:41
Agreed that it'd be good if sciline raised there. However, mypy does catch the case above so using mypy would already prevent those kinds of type errors, that might be one reason to let it slide.

**Comment by SimonHeybrock** [comment] 2024-02-07 07:50
That is not a reason, imho. `mypy` is a static analysis tool, whereas this is about a runtime check. We are currently far from passing mypy in any of the projects where we are using Sciline.

**Comment by jokasimr** [comment] 2024-02-07 08:20
Is the conclusion that this is something we want to implement? That is, making sciline raise in the case above when the requested type doesn't satisfy the constraints.

**Comment by SimonHeybrock** [comment] 2024-02-07 08:31
Yes.

**Comment by jokasimr** [comment] 2024-02-07 13:22
Encountered an interesting case when testing this.
Not sure if the implementation is wrong or if it is just the workflow that doesn't follow the stricter requirements we determined to implement here.

```python
# This is some of the code in esssans.types

BackgroundRun = NewType('BackgroundRun', int)
"""Background run: the run with only the solvent which the sample is placed in."""
EmptyBeamRun = NewType('EmptyBeamRun', int)
"""Run (sometimes called 'direct run') where the sample holder was empty.
It is used for reading the data from the transmission monitor."""
SampleRun = NewType('SampleRun', int)
"""Sample run: the run with the sample placed in the solvent inside the sample holder.
"""

RunType = TypeVar(
    'RunType',
    BackgroundRun,
    EmptyBeamRun,
    SampleRun,
)
"""TypeVar used for specifying BackgroundRun, EmptyBeamRun or SampleRun"""


class TransmissionRun(sciline.Scope[RunType, int], int):
    """Mapping between RunType and transmission run.
    In the case where no transmission run is provided, the transmission run should be
    the same as the measurement (sample or background) run."""

class CleanMonitor(
    sciline.ScopeTwoParams[RunType, MonitorType, sc.DataArray], sc.DataArray
):
    """Monitor data cleaned of background counts"""

# When requiring the result from the pipeline the following exception is raised:

# UnsatisfiedRequirement: ('No provider found for type', esssans.types.CleanMonitor[esssans.types.TransmissionRun[esssans.types.BackgroundRun], esssans.types.Transmission])
```

Is this the expected behavior?
It seems consistent with what we discussed above, `CleanMonitor` requires a `RunType` as the first type parameter and `TransmissionRun` is not a `RunType`.

**Comment by YooSunYoung** [comment] 2024-02-07 13:33
So it should be sth like this...?

```python 

class CleanMonitor(
    sciline.ScopeTwoParams[TransmissionRun[RunType], MonitorType, sc.DataArray], sc.DataArray
):
    """Monitor data cleaned of background counts"""
```

**Comment by SimonHeybrock** [comment] 2024-02-07 13:36
The workflow needs to be fixed, we were indeed not precise with the definition.

**Closed** 2024-02-13 14:19 UTC
