### ISSUE TITLE
Support Annotated types

### ISSUE THREAD

**Issue by jl-wynen** [scipp/sciline#125] opened 2024-02-14 12:16 UTC
Currently, annotated types are partly supported. They can be requested in providers and produced by providers like unannotated types. The reason is that Sciline removes the annotation and uses the underlying type: (tested with python 3.12)
```python
from typing import NewType, Annotated
import sciline as sl

Int = NewType('Int', int)
Str = NewType('Str', str)
AStr = Annotated[Str, 'metadata']


def foo(x: Int) -> AStr:
    return Str(str(x))


def bar(s: Str, a: AStr) -> list[str]:
    return [s, a]


pl = sl.Pipeline([foo, bar], params={Int: Int(3)})
# Can compute results:
print(pl.compute(Str))  # -> 3
print(pl.compute(list[str]))  # -> ['3', '3']

# But the annotation is lost in the graph:
g = pl.get(Str)
print(list(g._graph))  # -> [__main__.Str, __main__.Int]
g = pl.get(list[str])
print(list(g._graph))  # -> [list[str], __main__.Str, __main__.Int]
print(list(g._graph[list[str]].arg_spec.keys()))  # -> [__main__.Str, __main__.Str]

# Raises
# sciline.handler.UnsatisfiedRequirement: ('No provider found for type', typing.Annotated[__main__.Str, 'metadata'])
pl.compute(AStr)
```

I think this is the correct approach for running pipelines, Sciline should ignore annotations. But it would be useful to preserve the annotations, especially for inspecting task graphs.
And `pl.compute(AStr)` should work for parity with provider arguments.

**Comment by SimonHeybrock** [comment] 2024-02-14 12:19
Duplicate of #36?

**Comment by jl-wynen** [comment] 2024-02-14 12:38
Right. But with more details :package: Merging

**Closed** 2024-02-14 12:38 UTC
